import { LoadingScene } from './LoadingScene';
import { TitleScene } from './TitleScene';
import { CreditScene } from './CreditScene';
import { StageScene } from './StageScene';
import { St1_QuestionScene } from './St1_QuestionScene';
import { St1_AnswerScene } from './St1_AnswerScene';
import { St2_QuestionScene } from './St2_QuestionScene';
import { St2_AnswerScene } from './St2_AnswerScene';
import { EndingScene } from './EndingScene';
import { SettingsPopupScene } from './SettingsPopupScene';
export const Scenes = [LoadingScene, TitleScene, CreditScene, StageScene, St1_QuestionScene, St1_AnswerScene, St2_QuestionScene, St2_AnswerScene, EndingScene, SettingsPopupScene];